'use strict';

module.exports =
  angular.module('interval trainer', [
    'ui.bootstrap',
    'ui.router',
    'ngResource',
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    //useful directives, filters, services shared across the app
    require('../common').name,
    require('./account').name,
    require('./session').name,
    require('./sessions').name
    //load extra app modules here, e.g.:
    //require('./frontend').name,
    //require('./admin').name
  ]);
